### ISSUE TITLE
Graphic Icons look strange

### ISSUE THREAD

**Issue by anjohnson** [epics-base/website#28]
I like the updated website which is now much faster, but some of the logo-like Icons on pages such as the [7.0.2 release page](https://epics-controls.org/resources-and-support/base/epics-7/7-0-2/) look weird. Those images look wrong on the Wordpress media library page too, so it isn't necessarily the theme update that caused this — did the image files get corrupted somehow? I assume @epicDirk would be able to say whether they're meant to look like this, I would be surprised if they are.

**Comment by keijokorhonen** [comment]
They were looking normal in my browser (Firefox on OSX), but we were using a plugin which automatically converts images to the WebP format, which could have caused that. I have disabled it now. Could you look again and see whether they look fine now?

**Comment by ttkorhonen** [comment]
For reference, this is how they look in in my browser. They looked the same yesterday in my browser (same setup as Keijo's so no surprise).
![EPICSicons](https://user-images.githubusercontent.com/12592940/60866701-55e5e780-a229-11e9-9749-acdc71128e9b.png)

**Comment by ralphlange** [comment]
I could also see the distorted ones, and now they're back to normal.

**Comment by ralphlange** [comment]
Browser: Chrome.

**Comment by anjohnson** [comment]
Fixed now, thanks.

**Comment by anjohnson** [comment]
The distorted logos came back:
![image](https://user-images.githubusercontent.com/5453863/60913096-488e2480-a24c-11e9-9255-2b6b3967218d.png)
I'm running Chrome-74 on Linux.

**Comment by ralphlange** [comment]
Exactly the same here (Chrome 76 on ChromeOS).
The 7.0.2 page is fine, though.

**Comment by keijokorhonen** [comment]
Some of the icons were sourced from the sandbox website, so they looked like that. But I changed them, so do they look OK on your end?

I found this issue only on the Documents page, have you seen this anywhere else?

**Comment by ttkorhonen** [comment]
I still see one that looks strange, on the Documents page, "modules" shows a solid square instead of the - I do not know how to call it - "right" one. Also, the "base" icon seems to be pointing to the sandbox. I have not seen the issue elsewhere.

**Comment by keijokorhonen** [comment]
Should be fixed now.

**Comment by anjohnson** [comment]
All the icons on the Media library look fine on my iPad with Chrome. You might want to do a link search for any other places where icons are linked from the sandbox.

**Comment by keijokorhonen** [comment]
I found a couple other images that were sourced to the sandbox. All image sources should be fixed now.

**Comment by keijokorhonen** [comment]
Please reopen if you find any other images sourced from external websites.
